import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate} from 'react-router-dom';
import axios from 'axios';
import {Bot,BookOpen,Clock3,LogIn,LogOut,Menu,MessageSquare,Plus,Send,ShieldCheck,ThumbsDown,ThumbsUp,Upload,UserPlus} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
const client=axios.create({baseURL:API});
client.interceptors.request.use(c=>{const t=localStorage.getItem('p200_token');if(t)c.headers.Authorization=`Bearer ${t}`;return c});

function App(){
 const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('p200_user')||'null'));
 const [mode,setMode]=useState('login');
 if(!user) return <Auth mode={mode} setMode={setMode} onLogin={u=>setUser(u)}/>;
 return <Dashboard user={user} logout={()=>{localStorage.clear();setUser(null)}}/>;
}
function Auth({mode,setMode,onLogin}){
 const [form,setForm]=useState({name:'',email:'',password:''}); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 async function submit(e){e.preventDefault();setError('');setLoading(true);try{const url=mode==='login'?'/auth/login':'/auth/register';const {data}=await client.post(url,form);localStorage.setItem('p200_token',data.token);localStorage.setItem('p200_user',JSON.stringify(data.user));onLogin(data.user)}catch(e){setError(e.response?.data?.message||'Something went wrong')}finally{setLoading(false)}}
 return <div className="auth-shell"><div className="auth-card"><div className="brand"><div className="brand-icon"><Bot/></div><div><b>University AI</b><span>Student Support</span></div></div><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p className="muted">Ask university questions in natural language.</p><form onSubmit={submit}>{mode==='register'&&<input placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/>}<input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/><button className="primary" disabled={loading}>{mode==='login'?<LogIn size={18}/>:<UserPlus size={18}/>} {loading?'Please wait...':mode==='login'?'Login':'Register'}</button></form>{error&&<div className="error">{error}</div>}<button className="link-btn" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create an account':'Already have an account? Login'}</button></div></div>
}
function Dashboard({user,logout}){
 const [page,setPage]=useState('chat'); const [sessions,setSessions]=useState([]); const [active,setActive]=useState(null); const [messages,setMessages]=useState([]); const [mobile,setMobile]=useState(false);
 async function refreshSessions(){try{setSessions((await client.get('/chats')).data.sessions)}catch{}}
 useEffect(()=>{refreshSessions()},[]);
 async function openSession(id){setActive(id);setPage('chat');try{setMessages((await client.get(`/chats/${id}`)).data.messages)}catch{}}
 function newChat(){setActive(null);setMessages([]);setPage('chat');}
 return <div className="app"><aside className={`sidebar ${mobile?'open':''}`}><div className="side-brand"><Bot/> <span>University AI</span></div><button className="new-chat" onClick={newChat}><Plus size={17}/> New chat</button><nav><button className={page==='chat'?'active':''} onClick={()=>setPage('chat')}><MessageSquare/> Chat</button><button className={page==='history'?'active':''} onClick={()=>setPage('history')}><Clock3/> History</button>{user.role==='ADMIN'&&<button className={page==='admin'?'active':''} onClick={()=>setPage('admin')}><ShieldCheck/> Admin</button>}</nav><div className="side-bottom"><div className="user-mini"><div className="avatar">{user.name[0]}</div><div><b>{user.name}</b><span>{user.role}</span></div></div><button className="logout" onClick={logout}><LogOut size={17}/> Logout</button></div></aside><main className="main"><header><button className="menu" onClick={()=>setMobile(!mobile)}><Menu/></button><div><h2>{page==='chat'?'Student Support':page==='history'?'Chat History':'Admin Console'}</h2><span>AI-powered university assistant</span></div></header>{page==='chat'&&<Chat active={active} setActive={setActive} messages={messages} setMessages={setMessages} refreshSessions={refreshSessions}/>} {page==='history'&&<History sessions={sessions} openSession={openSession}/>} {page==='admin'&&<Admin/>}</main></div>
}
function Chat({active,setActive,messages,setMessages,refreshSessions}){
 const [input,setInput]=useState(''); const [busy,setBusy]=useState(false); const [feedback,setFeedback]=useState({});
 async function send(e){e?.preventDefault();const text=input.trim();if(!text||busy)return;setBusy(true);setInput('');setMessages(m=>[...m,{id:'tmp-u',sender:'user',text}]);try{const {data}=await client.post('/chat',{message:text,sessionId:active});setActive(data.sessionId);setMessages(m=>[...m.filter(x=>x.id!=='tmp-u'),data.message]);await refreshSessions()}catch(err){setMessages(m=>[...m.filter(x=>x.id!=='tmp-u'),{id:Date.now(),sender:'assistant',text:err.response?.data?.message||'Unable to reach the AI service.'}])}finally{setBusy(false)}}
 async function rate(m,r){setFeedback({...feedback,[m.id]:r});try{await client.post('/feedback',{messageId:m.id,rating:r})}catch{}}
 const quick=['What is the minimum attendance requirement?','How do I register for a course?','Where can I find course documents?','How do assignments work?'];
 return <section className="chat"><div className="messages">{messages.length===0?<div className="welcome"><div className="hero-icon"><Bot size={34}/></div><h1>How can I help you?</h1><p>Ask about academics, exams, attendance, documents, registration, assignments and more.</p><div className="quick">{quick.map(q=><button key={q} onClick={()=>setInput(q)}>{q}</button>)}</div></div>:messages.map((m,i)=><div key={m.id||i} className={`message ${m.sender}`}>{m.sender==='assistant'&&<div className="msg-icon"><Bot size={17}/></div>}<div className="bubble"><div>{m.text}</div>{m.meta?.sources?.length>0&&<div className="sources"><b>Sources</b>{m.meta.sources.slice(0,3).map(s=><span key={s.id}>📄 {s.source} · {s.category}</span>)}</div>}{m.sender==='assistant'&&m.id&&!m.id.toString().startsWith('tmp')&&<div className="feedback"><button className={feedback[m.id]==='helpful'?'chosen':''} onClick={()=>rate(m,'helpful')}><ThumbsUp size={14}/></button><button className={feedback[m.id]==='not_helpful'?'chosen':''} onClick={()=>rate(m,'not_helpful')}><ThumbsDown size={14}/></button></div>}</div></div>)}</div><form className="composer" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask a university question..."/><button className="send" disabled={busy}>{busy?'…':<Send size={19}/>}</button></form></section>
}
function History({sessions,openSession}){return <div className="panel"><h1>Your conversations</h1><p className="muted">Previous chatbot sessions.</p>{sessions.length===0?<div className="empty"><MessageSquare/><p>No conversations yet.</p></div>:<div className="session-list">{sessions.map(s=><button key={s.id} onClick={()=>openSession(s.id)}><MessageSquare size={17}/><span>{s.title}</span><small>{new Date(s.createdAt).toLocaleString()}</small></button>)}</div>}</div>}
function Admin(){const [files,setFiles]=useState([]);const [msg,setMsg]=useState('');async function load(){try{setFiles((await client.get('/admin/documents')).data.files)}catch(e){setMsg(e.response?.data?.message||'Admin access required')}}useEffect(()=>{load()},[]);async function upload(e){const f=e.target.files?.[0];if(!f)return;const fd=new FormData();fd.append('file',f);try{const r=await client.post('/admin/documents',fd,{headers:{'Content-Type':'multipart/form-data'}});setMsg(`Uploaded ${r.data.file}`);load()}catch(e){setMsg(e.response?.data?.message||'Upload failed')}}return <div className="panel"><h1>Knowledge Base</h1><p className="muted">Upload official university documents. The AI service will re-index them automatically.</p><label className="upload"><Upload size={20}/> Upload PDF / TXT / MD / JSON<input type="file" accept=".pdf,.txt,.md,.json" onChange={upload}/></label>{msg&&<div className="notice">{msg}</div>}<div className="file-list">{files.map(f=><div key={f}><BookOpen size={16}/>{f}</div>)}</div></div>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
